apiVersion: batch/v1
kind: Job
metadata:
  namespace: preemption-test
  name: reclaiming-job
  labels:
    kueue.x-k8s.io/queue-name: high-priority-lq
    kueue.x-k8s.io/priority-class: high-priority
spec:
  parallelism: 1
  completions: 1
  suspend: true
  template:
    metadata:
      annotations:
        kueue.x-k8s.io/priority: "80"
    spec:
      containers:
        - name: worker
          image: busybox:1.35
          command: ["sleep", "300"]
          resources:
            requests:
              cpu: 3 # 在 high-priority-cq 的名义配额 (4) 内
              memory: 6Gi # 在名义配额 (8Gi) 内
            limits:
              cpu: 3
              memory: 6Gi
      restartPolicy: Never
